name: Sync from Google Sheets

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force sync all rows from sheet"
        required: false
        default: "false"
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run sync script
        env:
          INPUT_FORCE: ${{ github.event.inputs.force }}
        run: python sync.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-sync new questions from Google Sheets" || echo "No changes to commit"
          git push
